Repository checkmo2025/CHECKMO-FE, pull requests merged in 2025-07, with the labels that each got.

#41 Feat-37: 책 추천 [목록 페이지/상세 페이지/등록 페이지] 등록 구현
  src/App.tsx
  src/apis/recommendApi.ts
  src/components/BookRecommend/BookRecommendCard.tsx
  src/components/BookRecommend/BookRecommendDetailCard.tsx
  src/components/BookRecommend/StarRating.tsx
  src/components/BookRecommend/StarSelector.tsx
  src/hooks/useRecommend.ts
  src/lib/axiosInstance.ts
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/BookRecommend/BookRecommendDetailPage.tsx
  src/pages/BookRecommend/BookRecommendHeader.tsx
  src/pages/BookRecommend/BookRecommendPage.tsx
  src/pages/BookRecommend/DummyRecommendDetail.tsx
  src/pages/BookRecommend/DummyRecommendList.tsx
  src/types/bookRecommend.ts
  src/types/dto.ts
Labels: ✏️ Rename, 🎉Feat, 🔨Refactor

#51 [style] 책 추천 카드 & 책 추천 상세 카드 디자인 수정
  package-lock.json
  package.json
  src/components/BookRecommend/BookRecommendCard.tsx
  src/components/BookRecommend/BookRecommendDetailCard.tsx
  src/components/BookRecommend/BookRecommendHeader.tsx
  src/pages/BookRecommend/BookRecommendPage.tsx
Labels: 🎨 Style

#60 [refactor] 로그인/회원가입/프로필 구조 수정
  public/assets/book-logo.png
  public/assets/character-logo.png
  public/assets/kakao-logo.png
  public/book-logo.png
  src/components/AlertModal.tsx
  src/components/AuthLeftPanel.tsx
  src/components/AuthRightTopTitle.tsx
  src/components/ReactivateAccountModal.tsx
  src/pages/Auth/LoginPage.tsx
  src/pages/Auth/ProfilePage.tsx
  src/pages/Auth/SignupPage.tsx
  src/utils/validators.ts
Labels: ⚙️Chore, 🎨 Style, 🔨Refactor

#67 [feat] sidebar 1개로 구현
  public/assets/icons/bookclub.png
  public/assets/icons/bookclub.svg
  public/assets/icons/bookstory.png
  public/assets/icons/bookstory.svg
  public/assets/icons/home.png
  public/assets/icons/home.svg
  public/assets/icons/likes.png
  public/assets/icons/mypage.png
  public/assets/icons/mypage.svg
  public/assets/icons/report.png
  public/assets/icons/search.png
  public/assets/icons/search.svg
  public/assets/icons/shortcut.png
  public/assets/icons/toggleClose.png
  public/assets/icons/toggleOpen.png
  src/App.tsx
  src/components/Main/BookStoriesCard.tsx
  src/components/Sidebar.tsx
  src/components/layout/Layout.tsx
  src/pages/test.tsx
Labels: ✅Test, 🎉Feat

#64 [feat] 독서모임 생성하기 UI 수정
  src/App.tsx
  src/pages/Main/CreateClubPage.tsx
Labels: 🎉Feat, 🎨 Style, 🔨Refactor

#89 [feat] 독서모임 - 모임페이지 구현
  public/chat-logo.png
  public/chess.png
  public/profile.png
  src/App.tsx
  src/apis/clubMeetingApi.ts
  src/components/BookRecommend/BookRecommendCreateCard.tsx
  src/components/Meeting/MeetingCard.tsx
  src/main.tsx
  src/pages/BookClub/Meeting/MeetingPage.tsx
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/BookRecommend/DummyRecommendDetail.tsx
  src/pages/BookRecommend/DummyRecommendList.tsx
  src/pages/Meeting/DummyMeetingDetail.tsx
  src/pages/Meeting/DummyMeetingList.tsx
  src/pages/Meeting/MeetingListPage.tsx
  src/router/rootRoutes.tsx
  src/types/apiResponse.ts
  src/types/clubMeeting.ts
  src/types/dto.ts
Labels: 🎉Feat, 🔨Refactor

#103 [feat] 독서 모임 - 모임 상세 페이지 구현
  src/App.tsx
  src/components/Meeting/TeamTopicSection.tsx
  src/components/Meeting/TopicCard.tsx
  src/components/Meeting/TopicPreviewSection.tsx
  src/pages/BookClub/MeetingNoticeDetailPage.tsx
  src/pages/Meeting/MeetingDetailPage.tsx
  src/pages/Meeting/MeetingListPage.tsx
  src/types/clubMeeting.ts
Labels: 🐞Fix, 🎉Feat

#104 [feat 100] 운영진-조 관리하기 페이지 구현
  src/App.tsx
  src/pages/Main/Info/OthersProfilePage.tsx
  src/pages/Manage/GroupManagementPage.tsx
Labels: 🎉Feat, 🔨Refactor

#108 [feat] 메인 공지사항 card 종류 추가 및 ui 수정
  src/components/Main/BookStoriesCard.tsx
  src/components/Main/Notices.tsx
  src/components/Main/Notices/AnnouncementCard.tsx
  src/components/Main/Notices/MeetingCard.tsx
  src/components/Main/Notices/NoticeCard.tsx
  src/components/Main/Notices/VoteCard.tsx
  src/pages/Main/HomePage.tsx
Labels: 🎉Feat, 🎨 Style, 🔨Refactor

#107 [Feat-57] BookRecommend 관련 페이지 및 컴포넌트 수정
  src/App.tsx
  src/components/BookRecommend/ActionButton.tsx
  src/components/BookRecommend/BookRecommendCreateCard.tsx
  src/components/BookRecommend/BookRecommendDetailCard.tsx
  src/components/BookRecommend/StarRating.tsx
  src/components/Modal.tsx
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/BookRecommend/BookRecommendDetailPage.tsx
  src/pages/BookRecommend/BookRecommendPage.tsx
  src/pages/BookRecommend/BookRecommendSearchPage.tsx
  src/pages/BookRecommend/SearchRecommendBookPage.tsx
  src/router/rootRoutes.tsx
Labels: 🐞Fix, ✏️ Rename, 🎉Feat, 🎨 Style, 🔨Refactor
