Repository checkmo2025/CHECKMO-FE, pull requests merged in 2025-08, with the labels that each got.

#120 [feat] 독서모임 - 모임 / 발제 전체보기 페이지 구현 및 컴포넌트 분리 & 구조 변경
  src/App.tsx
  src/components/Meeting/MeetingCard.tsx
  src/components/Meeting/TeamButtonList.tsx
  src/components/Meeting/TopicPreviewCard.tsx
  src/components/Meeting/TopicPreviewSection.tsx
  src/components/NonProfileHeader.tsx
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/Meeting/DummyMeetingDetail.tsx
  src/pages/Meeting/MeetingDetailPage.tsx
  src/pages/Meeting/MeetingListPage.tsx
  src/pages/Meeting/MeetingTopicListPage.tsx
Labels: 🎉Feat, 🎨 Style, 🔨Refactor

#118 [feat] 헤더 운영자 표시 추가+책 이야기 상세 라우트
  src/components/Header.tsx
  src/pages/Main/Info/My/MyStoryPage.tsx
  src/pages/Main/SearchPage.tsx
Labels: 🎉Feat, 🎨 Style, 🔨Refactor

#133 [refactor] 헤더 연결 및 스크롤 수정, 더미데이터 수정
  src/pages/BookClub/BookClubHomePage.tsx
Labels: 🔨Refactor

#135 [refactor] 독서모임 생성하기 페이지 스크롤 수정
  src/pages/Main/CreateClubPage.tsx
Labels: 🔨Refactor

#146 [refactor] 독서모임 공지사항 홈화면 스크롤 수정
  src/pages/BookClub/NoticePage.tsx
Labels: 🔨Refactor

#131 [feat] 독서모임 - 관리하기 - 독서모임 편집 페이지 구현
  src/App.tsx
  src/pages/BookClub/Club/ClubEditPage.tsx
Labels: 🎉Feat

#144 [feat] 운영진 독서모임 공지사항 홈화면 구현
  src/App.tsx
  src/components/BookClub/AnnouncementCard.tsx
  src/components/BookClub/AnnouncementList.tsx
  src/components/BookClub/NoticeCreateHoverMenu.tsx
  src/pages/Manage/NoticeManagementPage.tsx
Labels: 🎉Feat

#155 [refactor] 독서모임 검색 페이지 UI 수정
  src/components/SearchClub/ClubJoinAlertModal.tsx
  src/pages/Main/ClubSearchPage.tsx
Labels: ⚙️Chore, 🔨Refactor

#196 [feat] 메인 홈- 공지사항, 책 이야기 api 연동
  src/apis/BookStory/bookstories.ts
  src/apis/notices.ts
  src/components/Main/BookStoriesCard.tsx
  src/pages/Main/HomePage.tsx
  src/types/bookStories.ts
  src/types/notices.ts
Labels: 🎉Feat

#247 [fix] 공지사항 api 연동
  src/App.tsx
  src/apis/Main/clubs.ts
  src/apis/Main/notices.ts
  src/assets/icons/mainnotice.svg
  src/components/Main/Notices/AnnouncementCard.tsx
  src/components/Main/Notices/MeetingCard.tsx
  src/components/Main/Notices/NoticeCard.tsx
  src/components/Main/Notices/VoteCard.tsx
  src/pages/BookClub/Club/ClubEditPage.tsx
  src/pages/BookClub/NoticeCreatePage.tsx
  src/pages/Main/HomePage.tsx
  src/types/mainNotices.ts
Labels: 🐞Fix, 🎉Feat, 🎨 Style

#265 [style] 책 추천 관련 & 독서 모임 페이지 디자인 수정
  src/components/BookRecommend/ActionButton.tsx
  src/components/BookRecommend/BookRecommendCard.tsx
  src/components/BookRecommend/BookRecommendCreateCard.tsx
  src/components/BookRecommend/BookRecommendDetailCard.tsx
  src/components/BookRecommend/BookRecommendEditCard.tsx
  src/components/Meeting/MeetingCard.tsx
  src/components/NonProfileHeader.tsx
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/BookRecommend/BookRecommendEditPage.tsx
  src/pages/Meeting/MeetingDetailPage.tsx
  src/pages/Meeting/MeetingListPage.tsx
Labels: 🎨 Style

#268 style: svg 파일 png로 변경
  src/components/Main/Notices/AnnouncementCard.tsx
  src/components/Main/Notices/MeetingCard.tsx
  src/components/Main/Notices/VoteCard.tsx
Labels: 🎨 Style

#271 [style] 메인 홈+책 이야기 hover 스타일 변경 및 api 연동 데이터 유효성 처리
  src/apis/Main/clubs.ts
  src/apis/Main/notices.ts
  src/components/BookStory/MyBookStoryCard.tsx
  src/components/Main/BookStoriesCard.tsx
  src/components/Main/Notices/AnnouncementCard.tsx
  src/components/Main/Notices/MeetingCard.tsx
  src/components/Main/Notices/VoteCard.tsx
  src/components/Sidebar.tsx
  src/pages/Main/BookStory/BookStoryHomePage.tsx
  src/pages/Main/BookStory/MyBookStoryPage.tsx
  src/pages/Main/HomePage.tsx
Labels: bug, 🎨 Style

#282 [style] 각종 반응형 및 디자인 수정
  src/components/BookRecommend/BookRecommendCard.tsx
  src/components/BookRecommend/BookRecommendCreateCard.tsx
  src/components/BookRecommend/BookRecommendDetailCard.tsx
  src/components/BookRecommend/BookRecommendEditCard.tsx
  src/components/Meeting/MeetingCard.tsx
  src/components/NonProfileHeader.tsx
  src/components/Sidebar.tsx
  src/pages/Auth/ProfilePage.tsx
  src/pages/BookRecommend/BookRecommendCreatePage.tsx
  src/pages/BookRecommend/BookRecommendDetailPage.tsx
  src/pages/BookRecommend/BookRecommendEditPage.tsx
  src/pages/Meeting/MeetingCreatePage.tsx
  src/pages/Meeting/MeetingDetailPage.tsx
  src/pages/Meeting/MeetingListPage.tsx
Labels: 🐞Fix, 🎨 Style

#368 [style] 여러 스타일 수정
  package-lock.json
  package.json
  src/assets/icons/backIcon.png
  src/assets/images/clubSidebarImg.png
  src/components/Main/BookStoriesCard.tsx
  src/components/Modal.tsx
  src/components/Sidebar.tsx
  src/pages/Main/BookStory/MyBookStoryPage.tsx
  src/pages/Main/HomePage.tsx
  tailwind.config.js
Labels: 🐞Fix, ✏️ Rename, 🎨 Style, 🔨Refactor

#372 [feat] 책이야기 삭제 후 redirect + alert 삭제
  src/assets/icons/delete.png
  src/assets/icons/deleteHover.png
  src/assets/icons/edit.png
  src/assets/icons/editHover.png
  src/components/BookStory/MyBookStoryCard.tsx
  src/pages/Main/BookStory/BookStoryDetailPage.tsx
Labels: 🎉Feat

#374 [feat] 책이야기 삭제 후 redirect 동적으로 변경
  src/pages/Main/BookStory/BookStoryDetailPage.tsx
Labels: 🎉Feat
